### ISSUE TITLE
Make improvements based on conversation with George, 6 November 2023

### ISSUE THREAD

**Issue by alexwlchan** [Flickr-Foundation/flickypedia#175]
- [x] Always show the "X of Y" progress indicator, even if there's just one photo (https://github.com/Flickr-Foundation/flickypedia/pull/177)
- [x] Centre the portrait photos
- [x] Align photos to the top of the progress indicator
- [x] Sort out the plurals in the copy
- [x] "To Wikimedia Commons" instead of "To the … Entry" (https://github.com/Flickr-Foundation/flickypedia/pull/177)
- [x] Write a test for HTML in descriptions (#178)
- [x] Link the user name to the person's Flickr photo stream (https://github.com/Flickr-Foundation/flickypedia/pull/177)
- [x] Always show the "N characters remaining" indicator for short caption (#179)
- [x] Get rid of the "N more characters" for short caption (#179)
- [ ] Disable spellcheck on the categories field
- [x] Esc should dismiss the categories autoselect
- [x] Click should put the value in the field, not fill it in
- [ ] Mark new categories in the list with a "NEW" indicator (maybe) (start, yellow on lack, 0.6em, `<sup>`)
- [ ] Put the upload button on the left
- [x] Add a yellow warning box about CC0 metadata
- [ ] Line from the bookmarklet button to the bookmark bar?
- [ ] Prepend HTTPs for Flickr URLs in the get photos form, a la Flickypedia
- [ ] Build the commenting UI
- [x] Link the logo to the homepage (https://github.com/Flickr-Foundation/flickypedia/commit/82d7706d59b14f784b3f7226c09caa7401dc2300)
- [x] Add more space around the bookmarklet button (https://github.com/Flickr-Foundation/flickypedia/pull/177)
- [x] Bookmarklet should flag if it's not a Flickr URL (https://github.com/Flickr-Foundation/flickypedia/pull/177)
- [x] Empty title should dismiss any outstanding warnings (#179)
